/**
 * \file usart_serial.h
 *
 * Created: 2018-04-27 오후 2:17:58
 * Author: beeoh
 *
 * \brief  API file of USART as generated by Project Wizard
 *
 * Copyright (c) 2014 Atmel Corporation. All rights reserved.
 *
 *
 * \page License
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. The name of Atmel may not be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * 4. This software may only be redistributed and used in connection with an
 *    Atmel microcontroller product.
 *
 * THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 * \page license License
 * Copyright(c) 2014, Atmel Corporation All rights reserved.
 *
 * Licensed under Atmel's Limited License Agreement --> EULA.txt
 */


#ifndef USART_SERIAL_H
#define USART_SERIAL_H

#include "stdio.h"
# include "sio2host.h"



/**
 * \page wl_usart Quick Start Guide For Serial IO Module for Wireless Wizard	
 * This is a quick start guide for the usage of Serial IO(UART) Module 
 * \section wl_usart_mod Serial Module Usage
 * This module can be used to send and receive data using UART/USART.The \ref group_sio2host_uart is included by this module
 * All functionality provided by the \ref group_sio2host_uart can be used when this module is enabled by the wizard
 * Additionally the following functions are added as examples for usage send_usart_data() and read_usart_data()
 *
 */
/**
 * \brief This function transmits Debug Data to the terminal
 */
void send_usart_data(const char* testData);

/**
 * \brief This function performs a blocking one byte read functionality 
 */
char read_usart_data(void);

#endif